apiVersion: v1
kind: Service
metadata:
  name: apache-webserver-service
  labels:
    app: apache
spec:
  type: LoadBalancer
  selector:
    app: apache
  ports:
    - protocol: http
      port: 10000
      targetPort: 80
      NodePort: 30080
